model:
    arch: nasunet
data:
    dataset: promise12
    train_split: train_aug
    split: val
    img_rows: 'same'
    img_cols: 'same'
searching:
    init_channels: 16
    depth: 3
    epoch: 10
    batch_size: 2
    report_freq: 20
    n_workers: 2
    alpha_begin: 10
    gpu: True
    multi_gpus: False
    sharing_normal: True
    double_down_channel: True
    meta_node_num: 3
    grad_clip: 5
    train_portion: 0.7
    model_optimizer:
        name: 'sgd'
        lr: 0.025
        momentum: 0.9
        weight_decay: 3.0e-4
    arch_optimizer:
        name: 'adam'
        lr: 3.0e-4
        weight_decay: 1.0e-3
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    use_softmax_head: True
    resume:
training:
    geno_type: NASUNET
    init_channels: 32
    depth: 5
    epoch: 200
    batch_size: 6
    report_freq: 10
    n_workers: 2
    multi_gpus: False
    double_down_channel: False
    grad_clip: 3
    max_patience: 100
    model_optimizer:
        name: 'adam'
        lr: 1.0e-3
        weight_decay: 5.0e-4
    loss:
        name: 'dice_loss'
        aux: False
        aux_weight:
    backbone:
    lr_schedule:
        name: 'cos'
        T_max: 100
    resume: